name: cheshire
channels:
  - conda-forge
dependencies:
  - request
  - setuptools
  - pip:
    - flatdict
    - hjson
    - mako
    - pyyaml
    - tabulate
    - yapf
    - mkdocs
    - mkdocs-material
    - markdown-grid-tables
    - pyserial
    - numpy
