#!/usr/bin/env python3
# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#
# Generate a C header file containing a 2D int8_t weight matrix
# with random values for the RECKON accelerator.
#
# Usage:
#   python3 weights_gen.py --type winp --pre 6 --post 38 [--output winp.h] [--seed 42]

import argparse
import numpy as np
import os
import sys

VALID_TYPES = ("winp", "wrec", "wout")


def generate_weights(n_pre, n_post, seed=None):
    """Generate a (n_pre x n_post) matrix of int8 random weights.
    w ~ N(0, sqrt(2/n_pre)) * 127, then cast to int8."""
    if seed is not None:
        np.random.seed(seed)
    weights = np.random.randn(n_pre, n_post) * np.sqrt(2 / n_pre)
    weights = (weights * 127).astype(np.int8)
    return weights


def int8_to_hex(val):
    """Return a C hex literal string for a signed 8-bit value."""
    return "0x{:02X}".format(np.uint8(val))


def write_header(filepath, wtype, weights):
    """Write a C header containing the weight matrix definition."""
    n_pre, n_post = weights.shape
    guard = "__{}_H__".format(wtype.upper())

    with open(filepath, "w") as f:
        f.write("// Auto-generated by weights_gen.py -- do not edit\n")
        f.write("#ifndef {}\n".format(guard))
        f.write("#define {}\n\n".format(guard))
        f.write("#include <stdint.h>\n\n")
        f.write("#define {}_N_PRE  {}\n".format(wtype.upper(), n_pre))
        f.write("#define {}_N_POST {}\n\n".format(wtype.upper(), n_post))
        f.write(
            "int8_t {}[{}_N_PRE][{}_N_POST] = {{\n".format(
                wtype, wtype.upper(), wtype.upper()
            )
        )

        for i in range(n_pre):
            row_hex = ", ".join(int8_to_hex(weights[i][j]) for j in range(n_post))
            comma = "," if i < n_pre - 1 else ""
            f.write("    {{ {} }}{}\n".format(row_hex, comma))

        f.write("};\n\n")
        f.write("#endif // {}\n".format(guard))


def main():
    parser = argparse.ArgumentParser(
        description="Generate a random weight header file for RECKON"
    )
    parser.add_argument(
        "--type",
        required=True,
        choices=VALID_TYPES,
        help="Weight matrix type (winp, wrec, or wout)",
    )
    parser.add_argument(
        "--pre",
        required=True,
        type=int,
        help="Number of presynaptic neurons (rows)",
    )
    parser.add_argument(
        "--post",
        required=True,
        type=int,
        help="Number of postsynaptic neurons (columns)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output file path (default: <type>.h in current directory)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for reproducibility",
    )
    args = parser.parse_args()

    if args.pre <= 0 or args.post <= 0:
        print("Error: --pre and --post must be positive integers", file=sys.stderr)
        sys.exit(1)

    output = args.output if args.output else "{}.h".format(args.type)
    os.makedirs(os.path.dirname(output) or ".", exist_ok=True)

    weights = generate_weights(args.pre, args.post, args.seed)
    write_header(output, args.type, weights)

    print("Generated {}  ({}: {} x {})".format(output, args.type, args.pre, args.post))


if __name__ == "__main__":
    main()
